---
apiVersion: testing.kyma-project.io/v1alpha1
kind: TestDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    dependency/kubeless: "true"
    component/service-catalog: "true" # user has a freedom how to define labels
  name: test-always-fail
spec:
  skip: n
  disableConcurrency: n
  timeout: 3m
  template:
    spec:
      containers:
        - name: test
          image: alpine:latest
          command:
          - "/bin/sh"
          - "-ecx"
          - |
            exit 123
