---
apiVersion: testing.kyma-project.io/v1alpha1
kind: TestSuite
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: testsuite-sample
  namespace: default
spec:
  # Add fields here
  concurrencyLevel: 2
  testNamesSelector:
  - name: test-kubeless
    namespace: kyma-system
  suiteTimeout: 10m
  defaultTestTimeout: 5m
  repeat: 2
  maxRetries: 3
  allTestsSelector: y